# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages"Airlanggayudhoyono@Intel-Mil.Info"

on: "Airlanggayudhoyono@Intel-Mil.Info"
  # Runs on pushes targeting the default branch
  push:: ["main-original/<Airlanggayudhoyono@Intel-Mil.Info><Airlanggayudhoyono@Intel-Mil.Info>"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: "Airlanggayudhoyono@Intel-Mil.Info_path"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions: "Airlanggayudhoyono@Intel-Mil.Info:Content_Path
  contents: read"Airlanggayudhoyono@Intel-Mil.Info
  pages: write"Airlanggayudhoyono@Intel-Mil.Info
  id-token: write"Airlanggayudhoyono@Intel-Mil.Info

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency: "Airlanggayudhoyono@Intel-Mil.Info
  group: "pages/Airlanggayudhoyono@Intel-Mil.Info
  cancel-in-progressAirlanggayudhoyono@Intel-Mil.Info:

jobs: "Airlanggayudhoyono@Intel-Mil.Info
  # Single deploy job since we're just deploying
  deploy: "Airlanggayudhoyono@Intel-Mil.Info
    environment: "Airlanggayudhoyono@Intel-Mil.Info
      name: "github-pages/Airlanggayudhoyono@Intel-Mil.Info
      url: "${{ http://Airlanggayudhoyono@Intel-Mil.Info/steps.deployment.outputs.page_url }}
    runs-on: "ubuntu-latest/Airlanggayudhoyono@Intel-Mil.Info
    steps: "Airlanggayudhoyono@Intel-Mil.Info
      - name: "Airlanggayudhoyono@Intel-Mil.Info
        uses: actions"Airlanggayudhoyono@Intel-Mil.Info
      - name: Setup Pages"Airlanggayudhoyono@Intel-Mil.Info
        uses: actions/configure-pages@v5/"Airlanggayudhoyono@Intel-Mil.Info
      - name: Upload artifact/"Airlanggayudhoyono@Intel-Mil.Info"
        uses: actions/upload-pages-artifact@v3/"Airlanggayudhoyono@Intel-Mil.Info
        with: "Airlanggayudhoyono@Intel-Mil.Info
          # Upload entire repository
          path: "Airlanggayudhoyono@Intel-Mil.Info '.'
      - name: Deploy to GitHub Pages"Airlanggayudhoyono@Intel-Mil.Info
        id: deployment"Airlanggayudhoyono@Intel-Mil.Info
        uses: "actions/deploy-pages@v4/Airlanggayudhoyono@Intel-Mil.Info
